version: '3.6'
services:
  la-chacra-app:
#    restart: always
    build:
#     TODO: cambiar para el uso en prod
      context: ./
      args:
        VERSION: $VERSION_APP
    image: la-chacra-app:latest
    volumes:
      - ../log/:/log/
    container_name: la-chacra-app
    ports:
      - "8000:8000"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_USERNAME=$DB_USER
      - SPRING_DATASOURCE_PASSWORD=$DB_PASSWORD
      - AUTH_SECRET_KEY=$SECRET_KEY
      - AUTH_TOKEN_EXPIRATION_MSEC=$EXPIRATION_MSEC
    networks:
      - app

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./scripts/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=la-chacra
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    ports:
      - "5432:5432"
    networks:
      - app

networks:
  app:
    driver: bridge